apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
  namespace: dev
data:
  ENV: "dev"
  DB_HOST: "host.docker.internal"
  DB_PORT: "57901"
  DB_NAME: "myapp"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  PORT: "5000" 
  VITE_API_HOST: "host.docker.internal"
  VITE_API_PORT: "57863"
  VITE_API_PROTOCOL: "http"
