apiVersion: v1
kind: Pod
metadata:
  name: myapp-db-pod
  namespace: dev
  labels:
    app: database
spec:
  containers:
  - name: database-container
    image: dwivediavneesh386/database:1.0.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: DB_NAME
      value: myapp
    ports:
    - containerPort: 3306
