apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - targetPort: 3306
      port: 3307
      nodePort: 30008
