apiVersion: v1
kind: Service
metadata:
  name: myapp-frontend-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend-react
  ports:
    - targetPort: 80
      port: 81
      nodePort: 30009
