apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30008
